- name: Add repo to the image
  shell: |
    source /etc/profile.d/xcat.sh
    chdef -t osimage -o {{ genimage_name }} -p pkgdir=http://linux.mellanox.com/public/repo/mlnx_ofed_dpdk_upstream_libs/latest/rhel7.7/x86_64

- name: Add packages to the image
  lineinfile:
    state: present
    line: '{{ item }}'
    dest: {{ pkglist }}
  loop:
    - mlnx-ofed-dpdk-upstream-libs
    - infinipath-psm
